export const fieldLabels: Partial<Record<keyof Project, string>> = {
  scaleValue: "Total Value",
  recipientHumans: "Humans",
  recipientBirdsAndMammals: "Birds & Mammals",
  recipientFishAndReptiles: "Fish & Reptiles",
  recipientInvertebrates: "Crustaceans & Insects",
  determinacyExisting: "Existing beings",
  determinacySoon: "Beings who will soon exist",
  determinacyEver: "Beings who will someday exist",
  probFor10x: "...be really successful and create 10X amount of value?",
  probFor1x: "...be successful and create X amount of value?",
  probFor0x: "...have zero impact on the world?",
  probForMinus1x: "...backfire and have X amount of disvalue?",
  probForMinus10x: "...really backfire and have 10X amount of disvalue?",
  effectAddGood: "Create goods",
  effectRemoveBad: "Avert bads",
  valuePleasantness: "Pleasure and Pain",
  valueFlourishing: "Flourishing",
  valueEquity: "Justice and Equity",
};
