let id = -1;

const nextId = () => {
  id += 1;
  return id;
};

export const DEFAULT_PROJECT = {
  name: "Charitable Venture",
  description: "A project to improve the world.",
  id: nextId(),
  group: "Global Health and Development",
  scaleValue: 100,
  recipientHumans: 1,
  recipientBirdsAndMammals: 0,
  recipientFishAndReptiles: 0,
  recipientInvertebrates: 0,
  determinacyExisting: 0.9,
  determinacySoon: 0.1,
  determinacyEver: 0,
  probFor10x: 0.1,
  probFor1x: 0.7,
  probFor0x: 0.15,
  probForMinus1x: 0.04,
  probForMinus10x: 0.01,
  effectAddGood: 0.5,
  effectRemoveBad: 0.5,
  valuePleasantness: 0.45,
  valueFlourishing: 0.3,
  valueEquity: 0.25,
};

export const DEFAULT_PROJECTS = [
  {
    name: "Tuberculosis Initiative",
    description: `A project aimed at reducing rates of tuberculosis in developing countries.
    It has a high probability of alleviating a significant amount of suffering in humans
    with a high probability and allows for better overall welfare as a side effect.`,
    id: nextId(),
    group: "Global Health and Development",
    scaleValue: 60,
    recipientHumans: 1,
    recipientBirdsAndMammals: 0,
    recipientFishAndReptiles: 0,
    recipientInvertebrates: 0,
    determinacyExisting: 0.9,
    determinacySoon: 0.1,
    determinacyEver: 0,
    probFor10x: 0.1,
    probFor1x: 0.7,
    probFor0x: 0.15,
    probForMinus1x: 0.04,
    probForMinus10x: 0.01,
    effectAddGood: 0.1,
    effectRemoveBad: 0.9,
    valuePleasantness: 0.67,
    valueFlourishing: 0.31,
    valueEquity: 0.025,
  },
  {
    name: "Direct Transfers Everywhere",
    description: `A project that facilitates direct cash transfers to the world's most impoverished people.
    It has a very high probability of improving the welfare of humans in a variety of ways. `,
    id: nextId(),
    group: "Global Health and Development",
    scaleValue: 60,
    recipientHumans: 1,
    recipientBirdsAndMammals: 0,
    recipientFishAndReptiles: 0,
    recipientInvertebrates: 0,
    determinacyExisting: 0.9,
    determinacySoon: 0.1,
    determinacyEver: 0,
    probFor10x: 0.09,
    probFor1x: 0.8,
    probFor0x: 0.06,
    probForMinus1x: 0.04,
    probForMinus10x: 0.01,
    effectAddGood: 0.5,
    effectRemoveBad: 0.5,
    valuePleasantness: 0.32,
    valueFlourishing: 0.58,
    valueEquity: 0.1,
  },
  {
    id: nextId(),
    name: "AirScrubbers International",
    description: `A group devoted to promoting policy changes that improve air quality.
    It has a decent probability of preventing suffering. If successful, it will help both current and near-future humans and animals.`,
    group: "Global Health and Development",
    scaleValue: 80,
    recipientHumans: 0.5,
    recipientBirdsAndMammals: 0.25,
    recipientFishAndReptiles: 0.15,
    recipientInvertebrates: 0.1,
    determinacyExisting: 0.4,
    determinacySoon: 0.6,
    determinacyEver: 0,
    probFor10x: 0.16,
    probFor1x: 0.4,
    probFor0x: 0.4,
    probForMinus1x: 0.04,
    probForMinus10x: 0.0,
    effectAddGood: 0.1,
    effectRemoveBad: 0.9,
    valuePleasantness: 0.35,
    valueFlourishing: 0.35,
    valueEquity: 0.3,
  },
  {
    name: "People for the Just Treatment of Humans",
    description: `A project aimed at promoting human dignity and respectful treatment of individuals in diverse legal systems.
    It has a high probability of producing a modest short-term effect on welfare, but is geared more toward righting wrongs than improving wellbeing.`,
    id: nextId(),
    group: "Global Health and Development",
    scaleValue: 20,
    recipientHumans: 1,
    recipientBirdsAndMammals: 0,
    recipientFishAndReptiles: 0,
    recipientInvertebrates: 0,
    determinacyExisting: 0.9,
    determinacySoon: 0.05,
    determinacyEver: 0.05,
    probFor10x: 0.07,
    probFor1x: 0.75,
    probFor0x: 0.15,
    probForMinus1x: 0.02,
    probForMinus10x: 0.01,
    effectAddGood: 0.1,
    effectRemoveBad: 0.9,
    valuePleasantness: 0.07,
    valueFlourishing: 0.13,
    valueEquity: 0.8,
  },
  {
    id: nextId(),
    name: "Better Bangladesh",
    description: `A development initiative that aims to reduce the incidence of extreme poverty in Bangladesh.
    It has a decent chance of making a difference in human beings, with its effects including both alleviating suffering and encouraging human flourishing.`,
    group: "Global Health and Development",
    scaleValue: 70,
    recipientHumans: 1,
    recipientBirdsAndMammals: 0,
    recipientFishAndReptiles: 0,
    recipientInvertebrates: 0,
    determinacyExisting: 0.8,
    determinacySoon: 0.2,
    determinacyEver: 0,
    probFor10x: 0.19,
    probFor1x: 0.5,
    probFor0x: 0.14,
    probForMinus1x: 0.15,
    probForMinus10x: 0.02,
    effectAddGood: 0.3,
    effectRemoveBad: 0.7,
    valuePleasantness: 0.45,
    valueFlourishing: 0.45,
    valueEquity: 0.1,
  },
  {
    id: nextId(),
    name: "Sayonara Syphilis",
    description: `A biomedical research startup that aims to produce a low-cost syphilis vaccine.
    It is more likely than not to fail, but if successful would improve lives in a variety of ways.`,
    group: "Global Health and Development",
    scaleValue: 20,
    recipientHumans: 1,
    recipientBirdsAndMammals: 0,
    recipientFishAndReptiles: 0,
    recipientInvertebrates: 0,
    determinacyExisting: 0.7,
    determinacySoon: 0.3,
    determinacyEver: 0,
    probFor10x: 0.1,
    probFor1x: 0.36,
    probFor0x: 0.54,
    probForMinus1x: 0,
    probForMinus10x: 0,
    effectAddGood: 0.2,
    effectRemoveBad: 0.8,
    valuePleasantness: 0.25,
    valueFlourishing: 0.25,
    valueEquity: 0.5,
  },
  {
    name: "Artists without Borders",
    description: `A project to support free artistic expression in oppressed populations.
    It will encourage a relatively small amount of human flourishing and serve to improve equity.`,
    id: nextId(),
    group: "Global Health and Development",
    scaleValue: 20,
    recipientHumans: 1,
    recipientBirdsAndMammals: 0,
    recipientFishAndReptiles: 0,
    recipientInvertebrates: 0,
    determinacyExisting: 0.9,
    determinacySoon: 0.05,
    determinacyEver: 0.05,
    probFor10x: 0.21,
    probFor1x: 0.64,
    probFor0x: 0.1,
    probForMinus1x: 0.04,
    probForMinus10x: 0.01,
    effectAddGood: 1,
    effectRemoveBad: 0,
    valuePleasantness: 0.05,
    valueFlourishing: 0.65,
    valueEquity: 0.3,
  },
  {
    name: "Lawyers for Chickens",
    description: `A project that uses legal levers of power to improve the living conditions of chickens in factory farms.
    It has a small chance of improving the lives of a very large number of near-future chickens.`,
    id: nextId(),
    group: "Animal Welfare",
    scaleValue: 2000,
    recipientHumans: 0,
    recipientBirdsAndMammals: 1,
    recipientFishAndReptiles: 0,
    recipientInvertebrates: 0,
    determinacyExisting: 0,
    determinacySoon: 0.9,
    determinacyEver: 0.1,
    probFor10x: 0.01,
    probFor1x: 0.13,
    probFor0x: 0.85,
    probForMinus1x: 0.01,
    probForMinus10x: 0.0,
    effectAddGood: 0.01,
    effectRemoveBad: 0.99,
    valuePleasantness: 0.98,
    valueFlourishing: 0,
    valueEquity: 0.02,
  },
  {
    name: "Shrimp Welfare International",
    description: `A project that partners with fisheries to make cost-effective improvements to welfare.
    It has a modest chance of alleviating suffering in a huge number of shrimp.`,
    id: nextId(),
    group: "Animal Welfare",
    scaleValue: 8000,
    recipientHumans: 0,
    recipientBirdsAndMammals: 0,
    recipientFishAndReptiles: 0,
    recipientInvertebrates: 1,
    determinacyExisting: 0,
    determinacySoon: 1,
    determinacyEver: 0,
    probFor10x: 0.15,
    probFor1x: 0.28,
    probFor0x: 0.51,
    probForMinus1x: 0.05,
    probForMinus10x: 0.01,
    effectAddGood: 0.01,
    effectRemoveBad: 0.99,
    valuePleasantness: 1,
    valueFlourishing: 0,
    valueEquity: 0,
  },
  {
    id: nextId(),
    name: "Warm Thoughts for Wild Animals",
    description: `A group that tries to ensure that conservation efforts are sensitive to concerns about individual animal welfare.
    Has a small chance of making a difference to the harms caused in pursuit of other goods.`,
    group: "Animal Welfare",
    scaleValue: 400,
    recipientHumans: 0,
    recipientBirdsAndMammals: 0.6,
    recipientFishAndReptiles: 0.3,
    recipientInvertebrates: 0.1,
    determinacyExisting: 0.32,
    determinacySoon: 0.18,
    determinacyEver: 0.5,
    probFor10x: 0.03,
    probFor1x: 0.06,
    probFor0x: 0.86,
    probForMinus1x: 0.04,
    probForMinus10x: 0.01,
    effectAddGood: 0.5,
    effectRemoveBad: 0.5,
    valuePleasantness: 0.5,
    valueFlourishing: 0,
    valueEquity: 0.5,
  },
  {
    id: nextId(),
    name: "Passionate about Pests",
    description: `An animal welfare organization that lobbies against the worst pest management practices (sticky traps, anticoagulants, etc.).
    It has a moderate chance of alleviating a lot of suffering among diverse animals.`,
    group: "Animal Welfare",
    scaleValue: 600,
    recipientHumans: -0.001,
    recipientBirdsAndMammals: 0.51,
    recipientFishAndReptiles: 0.3,
    recipientInvertebrates: 0.2,
    determinacyExisting: 0.4,
    determinacySoon: 0.35,
    determinacyEver: 0.25,
    probFor10x: 0.11,
    probFor1x: 0.27,
    probFor0x: 0.52,
    probForMinus1x: 0.1,
    probForMinus10x: 0,
    effectAddGood: 0.01,
    effectRemoveBad: 0.99,
    valuePleasantness: 1,
    valueFlourishing: 0,
    valueEquity: 0,
  },
  {
    id: nextId(),
    name: "Happier Animals Now",
    description: `A general animal advocacy organization that lobbies against welfare-compromising agricultural practices and encourages people to transition to a plant-based diet. It has a small chance of improving the lives of diverse animals.`,
    group: "Animal Welfare",
    scaleValue: 300,
    recipientHumans: 0,
    recipientBirdsAndMammals: 0.6,
    recipientFishAndReptiles: 0.3,
    recipientInvertebrates: 0.1,
    determinacyExisting: 0.1,
    determinacySoon: 0.9,
    determinacyEver: 0,
    probFor10x: 0.08,
    probFor1x: 0.22,
    probFor0x: 0.7,
    probForMinus1x: 0.0,
    probForMinus10x: 0.0,
    effectAddGood: 0.1,
    effectRemoveBad: 0.9,
    valuePleasantness: 0.9,
    valueFlourishing: 0.1,
    valueEquity: 0.0,
  },
  {
    id: nextId(),
    name: "College Kindness Initiative",
    description: `An animal advocacy capacity-building project that recruits students at universities to the cause. It has a moderate chance of improving the lives of a diverse variety of animals.`,
    group: "Animal Welfare",
    scaleValue: 400,
    recipientHumans: 0,
    recipientBirdsAndMammals: 0.6,
    recipientFishAndReptiles: 0.3,
    recipientInvertebrates: 0.1,
    determinacyExisting: 0.1,
    determinacySoon: 0.9,
    determinacyEver: 0,
    probFor10x: 0.1,
    probFor1x: 0.3,
    probFor0x: 0.6,
    probForMinus1x: 0.0,
    probForMinus10x: 0.0,
    effectAddGood: 0.2,
    effectRemoveBad: 0.8,
    valuePleasantness: 0.9,
    valueFlourishing: 0.1,
    valueEquity: 0.0,
  },
  {
    name: "Svalbard Global Book Vault",
    description: `A project to create a repository of the world's knowledge in case of a catastrophic event.
    It has a very small chance of making a very big difference to far-future human flourishing.`,
    id: nextId(),
    group: "Speculative, Catastrophic, and Longtermist",
    scaleValue: 5000,
    recipientHumans: 1,
    recipientBirdsAndMammals: 0,
    recipientFishAndReptiles: 0,
    recipientInvertebrates: 0,
    determinacyExisting: 0,
    determinacySoon: 0,
    determinacyEver: 1,
    probFor10x: 0.001,
    probFor1x: 0.01,
    probFor0x: 0.989,
    probForMinus1x: 0,
    probForMinus10x: 0,
    effectAddGood: 0.8,
    effectRemoveBad: 0.2,
    valuePleasantness: 0,
    valueFlourishing: 0.95,
    valueEquity: 0.05,
  },
  {
    name: "The Hedonium Project",
    description: `A project to develop a trust supporting and sustaining AI server farms for running primitive happiness-maximizing algorithms. It has a very small chance of producing an astronomical amount of pleasure.`,
    id: nextId(),
    group: "Speculative, Catastrophic, and Longtermist",
    scaleValue: 200000,
    recipientHumans: 0,
    recipientBirdsAndMammals: 0,
    recipientFishAndReptiles: 1,
    recipientInvertebrates: 0,
    determinacyExisting: 0,
    determinacySoon: 0,
    determinacyEver: 1,
    probFor10x: 0.001,
    probFor1x: 0.001,
    probFor0x: 0.998,
    probForMinus1x: 0,
    probForMinus10x: 0,
    effectAddGood: 1,
    effectRemoveBad: 0,
    valuePleasantness: 1,
    valueFlourishing: 0,
    valueEquity: 0,
  },
  {
    name: "The Cassandra Fund",
    description: `A project to increase public awareness of existential threats in order to pass safety legislation. It has a very small chance of producing a tremendous amount of human flourishing in the far-future.`,
    id: nextId(),
    group: "Speculative, Catastrophic, and Longtermist",
    scaleValue: 100000,
    recipientHumans: 1,
    recipientBirdsAndMammals: 0,
    recipientFishAndReptiles: 0,
    recipientInvertebrates: 0,
    determinacyExisting: 0.01,
    determinacySoon: 0.01,
    determinacyEver: 0.98,
    probFor10x: 0.0015,
    probFor1x: 0.005,
    probFor0x: 0.992,
    probForMinus1x: 0.001,
    probForMinus10x: 0.0005,
    effectAddGood: 0.3,
    effectRemoveBad: 0.7,
    valuePleasantness: 0.1,
    valueFlourishing: 0.9,
    valueEquity: 0,
  },
  {
    id: nextId(),
    name: "Pandemics No More",
    description:
      "A group devoted to developing early warning systems for highly transmissible and deadly diseases. It has a small chance of making a difference to humans in the short and long term.",
    group: "Speculative, Catastrophic, and Longtermist",
    scaleValue: 600,
    recipientHumans: 1,
    recipientBirdsAndMammals: 0.0,
    recipientFishAndReptiles: 0.0,
    recipientInvertebrates: 0.0,
    determinacyExisting: 0.33,
    determinacySoon: 0.34,
    determinacyEver: 0.33,
    probFor10x: 0.02,
    probFor1x: 0.13,
    probFor0x: 0.8,
    probForMinus1x: 0.05,
    probForMinus10x: 0.0,
    effectAddGood: 0.05,
    effectRemoveBad: 0.95,
    valuePleasantness: 0.8,
    valueFlourishing: 0.1,
    valueEquity: 0.1,
  },
  {
    id: nextId(),
    name: "Soothsayers R Us",
    description:
      "An organization dedicated to studying forecasting and improving the results of the forecasting community. It has a small chance of diverse positive effects.",
    group: "Speculative, Catastrophic, and Longtermist",
    scaleValue: 600,
    recipientHumans: 1,
    recipientBirdsAndMammals: 0,
    recipientFishAndReptiles: 0,
    recipientInvertebrates: 0.0,
    determinacyExisting: 0.4,
    determinacySoon: 0.35,
    determinacyEver: 0.25,
    probFor10x: 0.03,
    probFor1x: 0.06,
    probFor0x: 0.86,
    probForMinus1x: 0.04,
    probForMinus10x: 0.01,
    effectAddGood: 0.5,
    effectRemoveBad: 0.5,
    valuePleasantness: 0.07,
    valueFlourishing: 0.73,
    valueEquity: 0.2,
  },
  {
    id: nextId(),
    name: "Don’t F𝔸𝕀L",
    description:
      "An effort to recruit especially talented undergraduate CS students to work on AI safety projects. It has a small chance of making a big difference to far-future humans.",
    group: "Speculative, Catastrophic, and Longtermist",
    scaleValue: 100000,
    recipientHumans: 1,
    recipientBirdsAndMammals: 0,
    recipientFishAndReptiles: 0,
    recipientInvertebrates: 0,
    determinacyExisting: 0.01,
    determinacySoon: 0.02,
    determinacyEver: 0.97,
    probFor10x: 0.004,
    probFor1x: 0.005,
    probFor0x: 0.988,
    probForMinus1x: 0.003,
    probForMinus10x: 0.0002,
    effectAddGood: 0.9,
    effectRemoveBad: 0.1,
    valuePleasantness: 0.1,
    valueFlourishing: 0.9,
    valueEquity: 0,
  },
];
